spring.application.name=proyecto

# ===== MYSQL EMPRESA =====
app.datasource.empresa.jdbc-url=${DB_EMPRESA_URL}
app.datasource.empresa.username=${DB_EMPRESA_USER}
app.datasource.empresa.password=${DB_EMPRESA_PASSWORD}
app.datasource.empresa.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== MYSQL LOCAL =====
app.datasource.local.jdbc-url=${DB_LOCAL_URL}
app.datasource.local.username=${DB_LOCAL_USER}
app.datasource.local.password=${DB_LOCAL_PASSWORD}
app.datasource.local.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

# ===== JWT =====
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=30
